/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TestimonialIndexRouteImport } from './routes/testimonial/index'
import { Route as EventsIndexRouteImport } from './routes/events/index'
import { Route as CausesIndexRouteImport } from './routes/causes/index'
import { Route as TestimonialThanksRouteImport } from './routes/testimonial/thanks'
import { Route as DonateClothesRouteImport } from './routes/donate/clothes'
import { Route as DonateBloodRouteImport } from './routes/donate/blood'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TestimonialIndexRoute = TestimonialIndexRouteImport.update({
  id: '/testimonial/',
  path: '/testimonial/',
  getParentRoute: () => rootRouteImport,
} as any)
const EventsIndexRoute = EventsIndexRouteImport.update({
  id: '/events/',
  path: '/events/',
  getParentRoute: () => rootRouteImport,
} as any)
const CausesIndexRoute = CausesIndexRouteImport.update({
  id: '/causes/',
  path: '/causes/',
  getParentRoute: () => rootRouteImport,
} as any)
const TestimonialThanksRoute = TestimonialThanksRouteImport.update({
  id: '/testimonial/thanks',
  path: '/testimonial/thanks',
  getParentRoute: () => rootRouteImport,
} as any)
const DonateClothesRoute = DonateClothesRouteImport.update({
  id: '/donate/clothes',
  path: '/donate/clothes',
  getParentRoute: () => rootRouteImport,
} as any)
const DonateBloodRoute = DonateBloodRouteImport.update({
  id: '/donate/blood',
  path: '/donate/blood',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/donate/blood': typeof DonateBloodRoute
  '/donate/clothes': typeof DonateClothesRoute
  '/testimonial/thanks': typeof TestimonialThanksRoute
  '/causes': typeof CausesIndexRoute
  '/events': typeof EventsIndexRoute
  '/testimonial': typeof TestimonialIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/donate/blood': typeof DonateBloodRoute
  '/donate/clothes': typeof DonateClothesRoute
  '/testimonial/thanks': typeof TestimonialThanksRoute
  '/causes': typeof CausesIndexRoute
  '/events': typeof EventsIndexRoute
  '/testimonial': typeof TestimonialIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/donate/blood': typeof DonateBloodRoute
  '/donate/clothes': typeof DonateClothesRoute
  '/testimonial/thanks': typeof TestimonialThanksRoute
  '/causes/': typeof CausesIndexRoute
  '/events/': typeof EventsIndexRoute
  '/testimonial/': typeof TestimonialIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/donate/blood'
    | '/donate/clothes'
    | '/testimonial/thanks'
    | '/causes'
    | '/events'
    | '/testimonial'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/donate/blood'
    | '/donate/clothes'
    | '/testimonial/thanks'
    | '/causes'
    | '/events'
    | '/testimonial'
  id:
    | '__root__'
    | '/'
    | '/donate/blood'
    | '/donate/clothes'
    | '/testimonial/thanks'
    | '/causes/'
    | '/events/'
    | '/testimonial/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DonateBloodRoute: typeof DonateBloodRoute
  DonateClothesRoute: typeof DonateClothesRoute
  TestimonialThanksRoute: typeof TestimonialThanksRoute
  CausesIndexRoute: typeof CausesIndexRoute
  EventsIndexRoute: typeof EventsIndexRoute
  TestimonialIndexRoute: typeof TestimonialIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/testimonial/': {
      id: '/testimonial/'
      path: '/testimonial'
      fullPath: '/testimonial'
      preLoaderRoute: typeof TestimonialIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/events/': {
      id: '/events/'
      path: '/events'
      fullPath: '/events'
      preLoaderRoute: typeof EventsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/causes/': {
      id: '/causes/'
      path: '/causes'
      fullPath: '/causes'
      preLoaderRoute: typeof CausesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/testimonial/thanks': {
      id: '/testimonial/thanks'
      path: '/testimonial/thanks'
      fullPath: '/testimonial/thanks'
      preLoaderRoute: typeof TestimonialThanksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/donate/clothes': {
      id: '/donate/clothes'
      path: '/donate/clothes'
      fullPath: '/donate/clothes'
      preLoaderRoute: typeof DonateClothesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/donate/blood': {
      id: '/donate/blood'
      path: '/donate/blood'
      fullPath: '/donate/blood'
      preLoaderRoute: typeof DonateBloodRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DonateBloodRoute: DonateBloodRoute,
  DonateClothesRoute: DonateClothesRoute,
  TestimonialThanksRoute: TestimonialThanksRoute,
  CausesIndexRoute: CausesIndexRoute,
  EventsIndexRoute: EventsIndexRoute,
  TestimonialIndexRoute: TestimonialIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
